### ISSUE TITLE
Error on module query

### ISSUE THREAD

**Issue by benji2512** [CianLR/dcu-past-papers#3]
Upon entering a module code in the text box and submitting, this error is returned on the page as shown in the image:
![SharedScreenshot](https://user-images.githubusercontent.com/12022823/71379716-3a4a7f80-25c4-11ea-9e3d-37c41c70caba.jpg) . I have copied the error in its entirety below:
 `Error: <!DOCTYPE html> <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]--> <!--[if IE 7]> <html class="no-js ie7 oldie" lang="en-US"> <![endif]--> <!--[if IE 8]> <html class="no-js ie8 oldie" lang="en-US"> <![endif]--> <!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]--> <head> <title>dcupastpapers.xyz | 502: Bad gateway</title> <meta charset="UTF-8" /> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" /> <meta name="robots" content="noindex, nofollow" /> <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" /> <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" /> <!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]--> <style type="text/css">body{margin:0;padding:0}</style> </head> <body> <div id="cf-wrapper"> <div id="cf-error-details" class="cf-error-details-wrapper"> <div class="cf-wrapper cf-error-overview"> <h1> <span class="cf-error-type">Error</span> <span class="cf-error-code">502</span> <small class="heading-ray-id">Ray ID: 549d1f2c1f86a67b &bull; 2019-12-23 20:35:24 UTC</small> </h1> <h2 class="cf-subheadline">Bad gateway</h2> </div><!-- /.error-overview --> <div class="cf-section cf-highlight cf-status-display"> <div class="cf-wrapper"> <div class="cf-columns cols-3"> <div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status "> <div class="cf-icon-error-container"> <i class="cf-icon cf-icon-browser"></i> <i class="cf-icon-status cf-icon-ok"></i> </div> <span class="cf-status-desc">You</span> <h3 class="cf-status-name">Browser</h3> <span class="cf-status-label">Working</span> </div> <div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status "> <div class="cf-icon-error-container"> <i class="cf-icon cf-icon-cloud"></i> <i class="cf-icon-status cf-icon-ok"></i> </div> <span class="cf-status-desc">Dublin</span> <h3 class="cf-status-name">Cloudflare</h3> <span class="cf-status-label">Working</span> </div> <div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source"> <div class="cf-icon-error-container"> <i class="cf-icon cf-icon-server"></i> <i class="cf-icon-status cf-icon-error"></i> </div> <span class="cf-status-desc">dcupastpapers.xyz</span> <h3 class="cf-status-name">Host</h3> <span class="cf-status-label">Error</span> </div> </div> </div> </div><!-- /.status-display --> <div class="cf-section cf-wrapper"> <div class="cf-columns two"> <div class="cf-column"> <h2>What happened?</h2> <p>The web server reported a bad gateway error.</p> </div> <div class="cf-column"> <h2>What can I do?</h2> <p>Please try again in a few minutes.</p> </div> </div> </div><!-- /.section --> <div class="cf-error-footer cf-wrapper"> <p> <span class="cf-footer-item">Cloudflare Ray ID: <strong>549d1f2c1f86a67b</strong></span> <span class="cf-footer-separator">&bull;</span> <span class="cf-footer-item"><span>Your IP</span>: 78.17.135.213</span> <span class="cf-footer-separator">&bull;</span> <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span> </p> </div><!-- /.error-footer --> </div><!-- /#cf-error-details --> </div><!-- /#cf-wrapper --> </body> </html>`
Would love to see it fixed(if possible) as its my go-to source for exam papers

**Comment by CianLR** [comment]
Should be back running now

**Comment by benji2512** [comment]
Yep, back up. Cheers Cian
